#!/usr/bin/env python3
"""
Gemma 3 270M OpenAI-Compatible API Server (Mock Version)

This is a mock server for testing the API endpoints without requiring the actual model.
Use this to verify API compatibility before deploying with the real model.

Usage:
    python api_server_mock.py --host 0.0.0.0 --port 8080
"""

import argparse
import json
import logging
import time
import random
from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
import uvicorn

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("gemma-api-mock")

# FastAPI app
app = FastAPI(
    title="Gemma 3 270M API (Mock)",
    description="OpenAI-compatible API mock for testing",
    version="1.0.0"
)

# Request/Response Models (OpenAI-compatible)
class ChatMessage(BaseModel):
    role: str
    content: str

class ChatCompletionRequest(BaseModel):
    model: str = "gemma-3-270m"
    messages: List[ChatMessage]
    temperature: float = 0.7
    top_p: float = 0.95
    top_k: int = 50
    max_tokens: Optional[int] = None
    stream: bool = False
    n: int = 1

class CompletionRequest(BaseModel):
    model: str = "gemma-3-270m"
    prompt: str
    temperature: float = 0.7
    top_p: float = 0.95
    top_k: int = 50
    max_tokens: Optional[int] = None
    stream: bool = False


# Mock responses for testing
MOCK_RESPONSES = [
    "This is a mock response from the Gemma 3 270M API. In a real deployment, this would be generated by the actual model.",
    "Hello! I'm a mock LLM response. The actual Gemma 3 270M model would provide more sophisticated responses.",
    "Thank you for your question! This is a simulated response for testing purposes.",
    "I understand your query. Here's a mock response to demonstrate the API format.",
]


def generate_mock_response(prompt: str, max_tokens: int = 256, temperature: float = 0.7) -> str:
    """Generate a mock response based on the prompt."""
    if "hello" in prompt.lower() or "hi" in prompt.lower():
        return "Hello! I'm a mock response from the Gemma 3 270M API. In production, the actual model would generate a more intelligent response based on your input."
    elif "how are you" in prompt.lower():
        return "I'm doing well, thank you for asking! This is a mock response to demonstrate the OpenAI-compatible API format."
    elif "what is" in prompt.lower():
        return "That's an interesting question! In a real deployment, the Gemma 3 270M model would provide a detailed answer. This mock response shows the API structure."
    else:
        return random.choice(MOCK_RESPONSES)


@app.get("/")
async def root():
    """Root endpoint with API information."""
    return {
        "name": "Gemma 3 270M API (Mock)",
        "version": "1.0.0",
        "description": "OpenAI-compatible API mock for testing",
        "docs": "/docs"
    }


@app.get("/v1/models")
async def list_models():
    """List available models (OpenAI-compatible endpoint)."""
    return {
        "object": "list",
        "data": [
            {
                "id": "gemma-3-270m",
                "object": "model",
                "owned_by": "gemma",
                "created": int(time.time())
            }
        ]
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """Chat completions endpoint (OpenAI-compatible)."""
    try:
        prompt = " ".join([msg.content for msg in request.messages])
        max_tokens = request.max_tokens or 256
        
        if request.stream:
            def stream_generator():
                response = generate_mock_response(prompt, max_tokens, request.temperature)
                tokens = response.split()
                
                for i, token in enumerate(tokens):
                    data = {
                        "id": f"chatcmpl-{int(time.time())}",
                        "object": "chat.completion.chunk",
                        "created": int(time.time()),
                        "model": request.model,
                        "choices": [
                            {
                                "delta": {"content": token + " "},
                                "index": 0,
                                "finish_reason": None
                            }
                        ]
                    }
                    yield f"data: {json.dumps(data)}\n\n"
                    time.sleep(0.05)
                
                final_data = {
                    "id": f"chatcmpl-{int(time.time())}",
                    "object": "chat.completion.chunk",
                    "created": int(time.time()),
                    "model": request.model,
                    "choices": [
                        {
                            "delta": {},
                            "index": 0,
                            "finish_reason": "stop"
                        }
                    ]
                }
                yield f"data: {json.dumps(final_data)}\n\n"
                yield "data: [DONE]\n\n"
            
            return StreamingResponse(stream_generator(), media_type="text/event-stream")
        else:
            response = generate_mock_response(prompt, max_tokens, request.temperature)
            
            return {
                "id": f"chatcmpl-{int(time.time())}",
                "object": "chat.completion",
                "created": int(time.time()),
                "model": request.model,
                "choices": [
                    {
                        "index": 0,
                        "message": {"role": "assistant", "content": response},
                        "finish_reason": "stop"
                    }
                ],
                "usage": {
                    "prompt_tokens": len(prompt.split()),
                    "completion_tokens": len(response.split()),
                    "total_tokens": len(prompt.split()) + len(response.split())
                }
            }
    
    except Exception as e:
        logger.error(f"Error in chat completion: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/v1/completions")
async def completions(request: CompletionRequest):
    """Text completions endpoint (OpenAI-compatible)."""
    try:
        max_tokens = request.max_tokens or 256
        
        if request.stream:
            def stream_generator():
                response = generate_mock_response(request.prompt, max_tokens, request.temperature)
                tokens = response.split()
                
                for token in tokens:
                    data = {
                        "id": f"cmpl-{int(time.time())}",
                        "object": "text_completion",
                        "created": int(time.time()),
                        "model": request.model,
                        "choices": [{"text": token + " ", "index": 0, "finish_reason": None}]
                    }
                    yield f"data: {json.dumps(data)}\n\n"
                    time.sleep(0.05)
                
                final_data = {
                    "id": f"cmpl-{int(time.time())}",
                    "object": "text_completion",
                    "created": int(time.time()),
                    "model": request.model,
                    "choices": [{"text": "", "index": 0, "finish_reason": "stop"}]
                }
                yield f"data: {json.dumps(final_data)}\n\n"
                yield "data: [DONE]\n\n"
            
            return StreamingResponse(stream_generator(), media_type="text/event-stream")
        else:
            response = generate_mock_response(request.prompt, max_tokens, request.temperature)
            
            return {
                "id": f"cmpl-{int(time.time())}",
                "object": "text_completion",
                "created": int(time.time()),
                "model": request.model,
                "choices": [{"text": response, "index": 0, "finish_reason": "stop"}],
                "usage": {
                    "prompt_tokens": len(request.prompt.split()),
                    "completion_tokens": len(response.split()),
                    "total_tokens": len(request.prompt.split()) + len(response.split())
                }
            }
    
    except Exception as e:
        logger.error(f"Error in completion: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "model": "gemma-3-270m", "mode": "mock"}


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Gemma 3 270M API Server (Mock)")
    parser.add_argument("--host", type=str, default="0.0.0.0", help="Host to bind to")
    parser.add_argument("--port", type=int, default=8080, help="Port to listen on")
    parser.add_argument("--workers", type=int, default=1, help="Number of worker processes")
    args = parser.parse_args()
    
    logger.info(f"Starting mock server on {args.host}:{args.port}")
    uvicorn.run(app, host=args.host, port=args.port, workers=args.workers)


if __name__ == "__main__":
    main()
